version: '3.1'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.yml
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/code:/usr/src/dvdrental_app
    environment:
      FLASK_DEBUG: "true"

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile.yml
    restart: always
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dvdrental -U postgres"]
      timeout: 2s
      retries: 10
    expose:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      