version: '3.1'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.yml
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/code:/usr/src/dvdrental-app
    environment:
      FLASK_DEBUG: "true"

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile.yml
    restart: always
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dvdrental -U postgres"]
      timeout: 2s
      retries: 10
    expose:
      - 5432:5432

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.yml
    volumes:
      - "./services/frontend:/usr/src/dvdrental-app"
      - "/usr/src/dvdrental-app/node_modules"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      