# syntax=docker/dockerfile:1
FROM python:3.12

WORKDIR /usr/src/dvdrental-app

ENV FLASK_APP=''
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8000

COPY ./code/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#COPY ./entrypoint.sh usr/src/dvdrental-app/entrypoint.sh
#RUN chmod +x usr/src/dvdrental-app/entrypoint.sh

EXPOSE 8000

CMD [ "flask", "run" ]

COPY ./code .