# syntax=docker/dockerfile:1
FROM python:3.12

WORKDIR /usr/src/dvdrental_app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV FLASK_ENV=development
ENV FLASK_APP=""
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8000

COPY ./code/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "flask", "run" ]

COPY ./code .